### ISSUE TITLE
Please Add `permissions_service.check_bulk_permissions`

### ISSUE THREAD

**Issue by MichaelCordingley** [authzed/authzed-rb#131]
The experimental service is in this client as of Nov. 2023, but not the final version that shipped as part of SpiceDB 1.30.0 in March 2024.

**Comment by tstirrat15** [comment]
@MichaelCordingley are you referring to [this?](https://github.com/authzed/authzed-rb/blob/main/lib/authzed/api/v1/permission_service_pb.rb#L39) It should be available.

**Comment by MichaelCordingley** [comment]
No. That's the message. There does not appear to be a way to _send_ that message to the server.

**Comment by tstirrat15** [comment]
Got it. Lemme dig. Thanks for letting us know!

**Comment by MichaelCordingley** [comment]
I'm using the client version 0.7.1 and ran this code to verify its non-existence:

```
[3] pry(main)> authzed_client.permissions_service.check_bulk_permissions
NoMethodError: undefined method `check_bulk_permissions' for #<Authzed::Api::V1::PermissionsService::Stub:0x000000012fd52818 @ch=#<GRPC::Core::Channel:0x0000000150a56f80>, @host="localhost:9090", @propagate_mask=nil, @timeout=1969-12-31 18:59:59 -0500, @interceptors=#<GRPC::InterceptorRegistry:0x0000000150a55e00 @interceptors=[#<Authzed::GrpcUtil::BearerToken:0x0000000150a5cef8 @token="presharedkey">]>>
from (pry):3:in `__pry__'
```

I don't see reference to this in the release notes for versions after 0.7.1, but can rerun this on the latest release tomorrow.

**Comment by MichaelCordingley** [comment]
Confirmed present on 0.11.0:

```
[2] pry(main)> authzed_client.permissions_service.check_bulk_permissions
ArgumentError: wrong number of arguments (given 0, expected 1..2)
from /Users/michael.cordingley/.asdf/installs/ruby/3.2.5/lib/ruby/gems/3.2.0/gems/grpc-1.66.0-arm64-darwin/src/ruby/lib/grpc/generic/service.rb:169:in `block (3 levels) in rpc_stub_class'
```

**Comment by tstirrat15** [comment]
It happened in #91, which was present in [this release](https://github.com/authzed/authzed-rb/releases/tag/v0.8.0). It looks like your version is just before that one.

**Comment by MichaelCordingley** [comment]
Appreciate the assist!
